prompts = [
    'a highly detailed epic cinematic concept art CG render digital painting artwork: Soviet cypher punk city, lightning storm. By Greg Rutkowski, in the style of Francis Bacon and Syd Mead and Norman Rockwell and Beksinski, open ceiling, highly detailed, painted by Francis Bacon and Edward Hopper, painted by James Gilleard, surrealism, airbrush, Ilya Kuvshinov, WLOP, Stanley Artgerm, very coherent, triadic color scheme, art by Takato Yamamoto and James Jean',
    'Sasquatch at the dj table dropping sick beats in the club , frightening, ghastly, photorealistic, old film, 35mm film, found film, scary, ominous,  by bruce davidson, on hasselblaad',
    'Panoramic painting of a glowing, volumetric nebula, luminous oil on canvas.',
    'a black man with long curly hair wearing glasses, walking out of a black hole, extreme detailed face, film still from the movie directed by Denis Villeneuve with art direction by Zdzisław Beksiński, wide lens ',
    'Julia Roberts is very annoyed while trying to sell a dress on Vinted. She is sited in front of a computer with the screen opened in the website of Vinted. She is in a large room and extremely irritated to the point of breaking the computer. In the background there are a lot of cartoon boxes and clothes everywhere. 50 mm, award winning photography in color.',
    'An orc smiling into the camera, portrait, artstation, by Alex Flores',
    'A detailed picture of a couple kissing, mosaic, yellow and gold color scheme, by Gustav Klimt',
    'futuristic space landscape by Jessica Rossier and HR Giger',
    'handmade illustration of an epic Vietnam war scene with a few american soldiers walking, the jungle at the background, some smoke and fire, blue sky with dramatic clouds, line art, ink, watercolor by Kilian Eng and by Jake Parker, heavy brushstrokes, winning-award masterpiece, fantastic, octane render, 8K HD Resolution, High quality image',
    'a stylized image of a robot holding a gun, a low poly render by Android Jones, featured on polycount, pixel art, voxel art, rendered in cinema4d, sketchfab',

    "An orc smiling into the camera, head-to-shoulder, artstation, realistic, highly detailed, bokeh, by Alex Flores, by Laurel D Austin, by Dave Rapoza",
    "three friends in an open convertible, roadtrip on route 66",
    " A three color offset photography of an hybrid object that combines conceptual ethnographic artifact, anthropology of wonder, and exotic artifacts, exhibition, collection, museum, 60s style",
    "the most beautiful stunning digital art imaginable",
    "Arnold Schwarzenegger is the captain of the starship Enterprise in the new Star Trek movie",
    "UFO hovering over medieval peasant standing in wheat field while grey alien approaches from the distance",
    "a goldfish swimming inside a cube made of water looking at its reflection on the side of the cube",
    "A beautiful woman with platinum blonde hair and green eyes and no makeup, full body portrait, highly detailed, excellent composition, dramatic lighting, realistic 4k",
    "Young man, lanky, pale, short black hair, wearing armor made of leather, holding a tankard of ale, digital art, realistic, detailed, trending on artstation, sea in the background",
    "Marilyn Monroe tries to sell a dress on Vinted",
]

questions = [
    'What type of city is portrayed in the image?',
    'Where is Sasquatch dropping a sick beat?',
    'What is glowing in this image?',
    'What type of hair does the black man have?',
    'What is Julia Roberts trying to sell on Vinted?',
    'What is smiling into the camera?',
    'What are the couple doing in this image?',
    'What type of futurist landscape is in this image?',
    'What ype of scene is in this image?',
    'What is holding a gun in this image?',

        "What is the expression of the Orc?",
        "How many people are in the vehicle?",
        "What is the stylistic time period of the image?",
        "What kind of art piece is this?",
        "Who is the famous person that is the subject of this image?",
        "Who is the person in this image?",
        "What is the shape of the water container that the goldfish is swimming in?",
        "What is the color of the woman's eyes?",
        "What is the type of armor the man is wearing?",
        "What is the woman in this picture doing?"
        ]

options = [
'A. old\nB. western\nC. Soviet\nD. dystopian',
'A. space\nB. forest\nC. club\nD. park',
'A. building\nB. nebula\nC. sun\nD. city',
'A. straight\nB. curly\nC. afro\nD. spiky',
'A. food\nB. tv\nC. car\nD. dress',
'A. orc\nB. rabbit\nC. man\nD. fish',
'A. running\nB. kissing\nC. talking\nD. playing',
'A. city\nB. country\nC. house\nD. space',
'A. war\nB. party\nC. funny\nD. calm',
'A. man\nB. woman\nC. robot\nD. criminal',

        "A. Fury\nB. Rage\nC. Fear\nD. Happy",
        "A. 1\nB. 2\nC. 3\nD. 4",
        "A. 1950s\nB. 1960s\nC. 1980s\nD. 2000s",
        "A. Digital art\nB. Oil painting\nC. 3D rendering in Blender\nD. Watercolor",
        "A. Sylvester Stallone\nB. Ronny Coleman\nC. Jay Cutler\nD. Franco Colombo\nE. Arnold Schwarzenegger",
        "A. Ancient hunter-gatherer\nB. Medieval nobility\nC. Medieval peasant\nD. Factory worker",
        "A. Cube shaped\nB. Round\nC. Oblong\nD. Triangular",
        "A. Green\nB. Blue\nC. Hazel\nD. Black",
        "A. Cloth\nB. Steel\nC. Bronze\nD. Leather",
        "A. Relaxing\nB. Sleeping\nC. Haggling\nD. Sewing"
        ]


answers = [
"C",
"C",
"B",
"B",
"D",
"A",
"B",
"D",
"A",
"C",

        "D",
        "C",
        "B",
        "A",
        "E",
        "C",
        "B",
        "A",
        "D",
        "C",
        ]

token = [
        14,
13,
9,
6,
11,
2,
7,
2,
7,
7,
        3,
        1,
        31,
        5,
        2,
        5,
        6,
        9,
        17,
        5,
        ]
